service:
  elbID: 161185be-1794-452b-82ca-647db0e9c5b1
  loadBalancerIP: 121.36.97.194

deployment:
  replicaCount: 1 #only support 1 now
  rsyncdImage: swr.cn-north-4.myhuaweicloud.com/openeuler/rsyncd:0.0.5
  image: swr.cn-north-4.myhuaweicloud.com/openeuler/nginx:1.17.5
  listenerImage: tommylike/repo-listener:0.1.2
  listenerUsername: openeuler
  listenerPassword: openeuler
  nginxConfig: config/nginx.conf
  defaultConfig: config/default.conf
  rsyncdConfig: config/rsyncd.conf
  rsyncSecrets: config/rsyncd.secrets
  sshPublicKey: config/ssh.pub

storage:
  size: 4000Gi
  className: ssd