---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openeuler-configmap
  namespace: repo2
data:
  rsyncd.secrets: |
    root:openeuler@1234
  ssh.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChSk+/FF79F8ut0hpNuYQ4uhAgUSY4hzRIPvQ2uVTukP0B0A99NYPfDNICp7gLa6e7yzaj+bvCpgWZoZCNAWTBWkq+zHTgDDHrLtUE4zPC1guzuR+Gz3yeIzSt0iAzi9uG2p+qh7jUfl8QAwNOs3wosNenoZj7NmgsCF9M1o85msimRc8Roxnn5caao1RtdNkDHDqhw5QiS9doSUjoxT+esD0CI7RHAyMgMCfSlXXl/phpdSU2hVJSFXsHVBTiymkuMQe8Ylmls+OEmCe8Cy7lIqE/Q+56l62Pxv4UJpOWs9T/SrOEr5vtEPGghZzgo5ViewzAs3dGMaODSO25XhrIiRZ7hjBK9tjLOX7ZXfAsb4DpJljq2aPCrlEaGJsHc2laixKIOKogDbqFffM3eXwgEAxPUevX/mYnuyhAVrsRUl8HXIQnTuVIEeYVdmn2MA8I/y6MPWdN5VbLR5gOiNLOuSVhCq3sQLpTZ9CONF+zq+1layCoaGMIZw5JwYgWCQgCGNclbx8eMVY3+J3slH6VjzE/05Eys18HtpuAMCivBLGgpBGeCVdpQqkHodTn5ZjNZEBAgzHypiOgR/txMHhkTi4+1ZvTmSRWs9hggv4/IcDQFaj1f2JVds6lxGvJyOnoy9k1VUC0q4N6sptpJ/n+ElCJ4UaHE48La3Mu79R6+Q== openeuler_hosts
  rsyncd.conf: |
    log file = /dev/stdout
    use chroot = yes
    uid = root
    gid = root
    max connections = 10
    timeout = 600
    read only = yes

    [openeuler]
            path = /repo/openeuler
            comment = openeuler repo folder
            read only = true
            auth users = root
            secrets file = /etc/rsyncd.secrets
            ignore nonreadable = yes
            refuse options = checksum
            dont compress = *
  default.conf: |
    server {
            listen 80;

            access_log  /var/log/nginx/host.access.log  main;
            server_name openeuler-repo.huawei.com;

            location / {
                root   /repo/openeuler;
                fancyindex on;
                fancyindex_exact_size off;
                autoindex   on;
            }
            location = /favicon.ico {
                      log_not_found off;
                      access_log off;
            }
    }
    server {
        listen 443 ssl;

        access_log  /var/log/nginx/host.access.log  main;

        server_name openeuler-repo.huawei.com;
        ssl on;
        ssl_certificate /etc/nginx/conf/ssl/fullchain.pem;
        ssl_certificate_key  /etc/nginx/conf/ssl/privkey.pem;

        location / {
            root   /repo/openeuler;
            fancyindex on;
            fancyindex_exact_size off;
            autoindex   on;
        }

        location = /favicon.ico {
                   log_not_found off;
                   access_log off;
        }
    }

  nginx.conf: |-
    user  root;
    worker_processes  6;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/conf/mime.types;
        default_type  application/octet-stream;
        server_tokens off;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf/conf.d/*.conf;
    }



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-data-volume
  namespace: repo2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4000Gi
  storageClassName: ssd
# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openeuler
  namespace: repo2
  labels:
    app: repo-nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo-nginx-pod
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      containers:
        - name: repo-nginx
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/nginx-extras:1.10.3
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: website-secrets-volume
              mountPath: /etc/nginx/conf/ssl/fullchain.pem
              subPath: fullchain.pem
            - name: website-secrets-volume
              mountPath: /etc/nginx/conf/ssl/privkey.pem
              subPath: privkey.pem
            - mountPath: /etc/nginx/conf/nginx.conf
              name: repo-nginx-configmap-volume
              subPath: nginx.conf
            - mountPath: /etc/nginx/conf/conf.d/default.conf
              name: repo-nginx-configmap-volume
              subPath: default.conf
            - mountPath: /repo/openeuler
              name: openeuler-data-volume
          resources:
            requests:
              cpu: 6000m
              memory: 8000Mi
        - name: rsync-server
          image: swr.cn-north-4.myhuaweicloud.com/openeuler/rsyncd:0.0.5
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /etc/rsyncd.conf
              name: repo-nginx-configmap-volume
              subPath: rsyncd.conf
            - mountPath: /etc/rsyncd.secrets.ro
              name: repo-nginx-configmap-volume
              subPath: rsyncd.secrets
            - mountPath: /repo/openeuler
              name: openeuler-data-volume
            - mountPath: /root/.ssh/authorized_keys.ro
              name: repo-nginx-configmap-volume
              subPath: ssh.pub
          resources:
            requests:
              cpu: 6000m
              memory: 6000Mi
          command:
            - /bin/sh
            - -c
            - |
              cp /etc/rsyncd.secrets.ro /etc/rsyncd.secrets
              chmod 0400 /etc/rsyncd.secrets
              cp /root/.ssh/authorized_keys.ro /root/.ssh/authorized_keys
              chmod 0400 /root/.ssh/authorized_keys
              chown root:root /root/.ssh/authorized_keys
              /usr/sbin/sshd &
              exec /usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf;
      volumes:
        - name: repo-nginx-configmap-volume
          configMap:
            name: openeuler-configmap
        - name: openeuler-data-volume
          persistentVolumeClaim:
            claimName: openeuler-data-volume
        - name: website-secrets-volume
          secret:
            secretName: website-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: openeuler-service
  namespace: repo2
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 161185be-1794-452b-82ca-647db0e9c5b1
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 443
      name: nginx-repo-https
      targetPort: 443
    - port: 873
      name: rsync-server-port
      targetPort: 873
    - port: 80
      name: nginx-repo-http
      targetPort: 80
    - port: 22
      name: rsync-ssh-server-port
      targetPort: 22
  selector:
    app: repo-nginx-pod
  type: LoadBalancer
  loadBalancerIP: 121.36.97.194
