---
# Source: repo-chart/templates/namespace.yaml
# Namespace for repo server
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: repo
  name: repo

---
# Source: repo-chart/templates/config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openeuler-configmap
  namespace: repo
data:
#  update-repo-job.yaml: |
#    apiVersion: batch/v1
#    kind: Job
#    metadata:
#      name: update-repo-job
#      namespace: repo
#    spec:
#      template:
#        spec:
#          containers:
#            - name: update-repo
#              image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/repo-tools:0.0.3
#              # NOTE: PROJECT_VARIABLE is used to be replaced with actual project list, don't update this only at this place.
#              args: ["--repo-json", "PROJECT_VARIABLE", "update"]
#              volumeMounts:
#                - mountPath: /repo/openeuler
#                  name: repo-data-volume
#              env:
#                - name: WORKING_DIR
#                  value: /repo/openeuler/repository
#          restartPolicy: Never
#          volumes:
#            - name: repo-data-volume
#              persistentVolumeClaim:
#                claimName: cce-efs-import-k410ji5h-hinm
  default.conf: |
    server {
        listen 443 ssl;

        access_log  /var/log/nginx/host.access.log  main;

        server_name repo.openeuler.org;
        ssl on;
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key  /etc/nginx/ssl/privkey.pem;

        location / {
            root   /repo/openeuler;
            autoindex   on;
        }

        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

  nginx.conf: |-
    user  root;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }



---
# Source: repo-chart/templates/deployment.yaml
# Persistent volume claim for deployment
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: openeuler-data-volume
#  namespace: repo
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 100Gi
#  storageClassName: sas

# ServiceAccount for deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openeuler-listener
  namespace: repo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openeuler-listener
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openeuler-listener
subjects:
  - kind: ServiceAccount
    name: openeuler-listener
    namespace: repo
roleRef:
  kind: ClusterRole
  name: openeuler-listener
  apiGroup: rbac.authorization.k8s.io


# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openeuler
  namespace: repo
  labels:
    app: repo-nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repo-nginx-pod
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      serviceAccount: openeuler-listener
      containers:
        - name: repo-nginx
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/nginx:1.17.5
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: website-secrets-volume
              mountPath: /etc/nginx/ssl/fullchain.pem
              subPath: fullchain.pem
            - name: website-secrets-volume
              mountPath: /etc/nginx/ssl/privkey.pem
              subPath: privkey.pem
            - mountPath: /etc/nginx/nginx.conf
              name: repo-nginx-configmap-volume
              subPath: nginx.conf
            - mountPath: /etc/nginx/conf.d/default.conf
              name: repo-nginx-configmap-volume
              subPath: default.conf
            - mountPath: /repo/openeuler
              name: repo-data-volume
        - name: repo-update-listener
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/repo-listener:0.0.2
          env:
            # base auth for repo listener
            - name: BASIC_AUTH_USERNAME
              value: openeuler
            - name: BASIC_AUTH_PASSWORD
              value: openeuler
            - name: K8S_NAMESPACE
              value: repo
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /etc/repo-update/update-repo-job.yaml
              name: repo-nginx-configmap-volume
              subPath: update-repo-job.yaml
      volumes:
        - name: repo-nginx-configmap-volume
          configMap:
            name: openeuler-configmap
        - name: repo-data-volume
          persistentVolumeClaim:
            claimName: cce-efs-import-for-repo-use
        - name: website-secrets-volume
          secret:
            secretName: website-secrets

---
# Source: repo-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: openeuler-service
  namespace: repo
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 161185be-1794-452b-82ca-647db0e9c5b1
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 443
      name: nginx-repo-https
      targetPort: 443
    - port: 80
      name: nginx-repo-listener-http
      targetPort: 80
  selector:
    app: repo-nginx-pod
  type: LoadBalancer
  loadBalancerIP: 121.36.97.194
