apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab:1.15.2.2
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: GITLAB_TIMEZONE
          value: Asia/Shanghai
        - name: GITLAB_SECRETS_DB_KEY_BASE
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-secrets-db-key-base
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-secrets-secret-key-base
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-secrets-otp-key-base
        - name: GITLAB_ROOT_PASSWORD
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-root-password
        - name: GITLAB_ROOT_EMAIL
          value: template@example.com # 需要手动修改

        - name: GITLAB_EMAIL
          value: template@example.com # 需要手动修改
        - name: GITLAB_EMAIL_REPLY_TO
          value: noreply@example.com # 需要手动修改
        - name: GITLAB_INCOMING_EMAIL_ADDRESS
          value: reply@example.com # 需要手动修改

        - name: GITLAB_HOST
          value: template.host.com # 需要手动修改
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgres fake ip # 需要手动修改
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: postgres-password
        - name: DB_NAME
          value: postgres

        - name: REDIS_HOST
          value: redis fake ip # 需要手动修改
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "true"
        - name: SMTP_DOMAIN
          value: template-smtp.com # 需要手动修改
        - name: SMTP_HOST
          value: smtp.template.com # 需要手动修改
        - name: SMTP_PORT
          value: smtp fake port # 需要手动修改
        - name: SMTP_USER
          value: template@example.com # 需要手动修改
        - name: SMTP_PASS
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: smtp-password
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "true"
        - name: IMAP_HOST
          value: imap.template.com # 需要手动修改
        - name: IMAP_PORT 
          value: imap fake port # 需要手动修改
        - name: IMAP_USER
          value: template@example.com # 需要手动修改
        - name: IMAP_PASS 
          valueFrom: # 需要手动修改
            secretKeyRef:
              name: gitlab-secrets
              key: imap-password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "true"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: gitlab-data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: tempalte-gitlab-data # 需要手动修改
