
groups:
- name: test
  rules:
  - alert: memery 使用率过高 快来救火啦！！！
    expr: 100-(node_memory_Buffers_bytes+node_memory_Cached_bytes+node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100 > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 内存使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}内存使用率超过80%,当前使用率[{{ $value }}]."

  - alert: cpu使用率过高 快来救火啦！！
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle"}[30m])) without(cpu)*100 > 90
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} cpu使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}cpu使用率超过90%,当前使用率[{{ $value }}]."

  - alert: disk空间不足啦  快来救火啦！！
    expr: 100-(node_filesystem_free_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"})*100 > 90
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} disk使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}disk使用率超过90%,当前使用率[{{ $value }}]."

  - alert: 进程挂啦！  快来救火啦！！
    expr: sum(namedprocess_namegroup_states{groupname=~"ssh|sshd",state!="Zombie"})without(state) < 1
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.groupname }} 进程挂啦"
      description: "{{ $labels.instance }} of job {{$labels.job}}进程{{ $labels.groupname }}数为0，当前进程数[{{ $value }}]."

  - alert: mysql 进程挂啦！  快来救火啦！！
    expr: namedprocess_namegroup_num_procs{groupname="mysqld",host=~"obs-api-server|obs-backend-server"} < 1
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.groupname }} 进程挂啦"
      description: "{{ $labels.instance }} of job {{$labels.job}}进程{{ $labels.groupname }}数为0，当前进程数[{{ $value }}]."

  - alert: target 挂啦！  快来救火啦！！
    expr: up==0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.host }} target挂啦"
      description: "{{ $labels.instance }} of job {{$labels.job}}  target挂啦，当前target数为[{{ $value }}]."
