---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
    {{- (.Files.Glob .Values.deployment.defaultConfig).AsConfig | nindent 2 }}
    {{- (.Files.Glob .Values.deployment.nginxConfig).AsConfig | nindent 2 }}
