# Persistent volume claim for deployment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-volume
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.className }}

# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: repo-nginx-server
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: repo-nginx-pod
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      containers:
        - name: repo-nginx
          image: {{ .Values.deployment.image }}
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: website-secrets-volume
              mountPath: /etc/nginx/ssl/fullchain.pem
              subPath: fullchain.pem
            - name: website-secrets-volume
              mountPath: /etc/nginx/ssl/privkey.pem
              subPath: privkey.pem
            - mountPath: /etc/nginx/nginx.conf
              name: repo-nginx-configmap-volume
              subPath: nginx.conf
            - mountPath: /etc/nginx/conf.d/default.conf
              name: repo-nginx-configmap-volume
              subPath: default.conf
            - mountPath: /repo/openeuler
              name: openeuler-data-volume
          resources:
            requests:
              cpu: 4000m
              memory: 8000Mi
        - name: rsync-server
          image: {{ .Values.deployment.rsyncdImage }}
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /etc/rsyncd.conf
              name: repo-nginx-configmap-volume
              subPath: rsyncd.conf
            - mountPath: /etc/rsyncd.secrets.ro
              name: repo-nginx-configmap-volume
              subPath: rsyncd.secrets
            - mountPath: /repo/openeuler
              name: openeuler-data-volume
            - mountPath: /root/.ssh/authorized_keys.ro
              name: repo-nginx-configmap-volume
              subPath: ssh.pub
          resources:
            requests:
              cpu: 4000m
              memory: 6000Mi
          command:
            - /bin/sh
            - -c
            - |
              cp /etc/rsyncd.secrets.ro /etc/rsyncd.secrets
              chmod 0400 /etc/rsyncd.secrets
              cp /root/.ssh/authorized_keys.ro /root/.ssh/authorized_keys
              chmod 0400 /root/.ssh/authorized_keys
              chown root:root /root/.ssh/authorized_keys
              /usr/sbin/sshd &
              exec /usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf;
      volumes:
        - name: repo-nginx-configmap-volume
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: openeuler-data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-volume
        - name: website-secrets-volume
          secret:
            secretName: website-secrets
