apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.service.elbID }}
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      name: nginx-repo-http
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: repo-nginx-pod
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}