apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: {{ .Values.service.elbID }}
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 443
      name: nginx-repo-https
      targetPort: 443
    - port: 80
      name: nginx-repo-listener-http
      targetPort: 80
  selector:
    app: repo-nginx-pod
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}