apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 97f3ed50-3c81-403b-adb0-6e70094bb1e4
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  creationTimestamp: 2019-12-11T03:38:06Z
  labels:
    app: grafana
    name: grafana
  name: grafana
  namespace: monitoring
  resourceVersion: "25308703"
  selfLink: /api/v1/namespaces/monitoring/services/grafana
  uid: a4ec0d31-1bc7-11ea-b53d-fa163eb8d9d5
spec:
  clusterIP: 10.247.94.128
  externalTrafficPolicy: Cluster
  loadBalancerIP: 119.8.45.72
  ports:
  - name: cce-service-0
    nodePort: 31919
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 119.8.45.72
