## define the jenkins data volume 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-data-pvc
  namespace: ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ssd
  volumeMode: Filesystem

