---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcore
  namespace: maillist
  labels:
    app: maillist
  annotations:
    version: ~1.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: maillist
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: maillist
    spec:
      containers:
      - name: mail-core
        image: swr.cn-north-1.myhuaweicloud.com/openeuler/mail-core:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8024
          name: mailport
          protocol: TCP

